### ISSUE TITLE
Cannot start service.

### ISSUE THREAD

**Issue by NiNiyas** [fpiesche/docker-woodpecker#30]
Hi! Thanks for the arm64 version, but when I try to run it, it shows `ERROR: for woodpecker-agent  Cannot start service woodpecker-agent: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "agent": executable file not found in $PATH: unknown`
This is the docker-compose I'm using:
```
  woodpecker-agent:
    container_name: WoodpeckerRunner
    image: florianpiesche/woodpecker-agent:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_SECRET=blahblahblah
 ```
Can you help me please?
